name: unit tests

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: '8.0.x'
           dotnet-quality: 'preview'

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test WhoisClient.NET.Test -l "console;verbosity=normal" -v:q -f net6.0 --nologo
